const K='pureAIWardrobeFresh',RESET='pureAIWardrobeResetV4',IMGDB='pureAIWardrobeImages';
let db=JSON.parse(localStorage.getItem(K)||'{"items":[],"diary":[],"queue":[]}');
db.items??=[];db.diary??=[];db.queue??=[];
if(localStorage.getItem(RESET)!=='1'){db.items=[];localStorage.setItem(K,JSON.stringify(db));localStorage.setItem(RESET,'1');}
const cats=['全部','上衣','下身','洋裝','外套','鞋子','包包','襪子','配件','其他'];let cat='全部';
const save=()=>{try{localStorage.setItem(K,JSON.stringify(db));return true}catch(e){console.error(e);toast('儲存空間不足，請重新整理頁面後再試');return false}};
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const toast=t=>{let e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
const read=f=>new Promise((r,j)=>{let x=new FileReader();x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)});
const clearInput=id=>{let e=document.getElementById(id);if(e)e.value=''};
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));let t=document.getElementById(id);if(t)t.classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));document.getElementById('n-'+id)?.classList.add('on');render();scrollTo({top:0,behavior:'smooth'})}
function uid(){return crypto.randomUUID?.()||Date.now()+Math.random()}
function openImgDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open(IMGDB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveSourcePhotos(files){let dbi=await openImgDB(),session=uid();return new Promise((resolve,reject)=>{let tx=dbi.transaction('photos','readwrite'),st=tx.objectStore('photos');files.forEach((f,i)=>st.put(f,session+':'+(i+1)));tx.oncomplete=()=>{dbi.close();resolve(session)};tx.onerror=()=>{dbi.close();reject(tx.error)}})}
async function getSourcePhoto(session,index){if(!session||!index)return null;let dbi=await openImgDB();return new Promise((resolve,reject)=>{let r=dbi.transaction('photos').objectStore('photos').get(session+':'+index);r.onsuccess=()=>{dbi.close();resolve(r.result||null)};r.onerror=()=>{dbi.close();reject(r.error)}})}
function cropBlob(blob,crop){return new Promise((resolve,reject)=>{if(!blob)return resolve('');let im=new Image();im.onload=()=>{try{let x=Math.max(0,Math.min(1000,Number(crop?.x??0))),y=Math.max(0,Math.min(1000,Number(crop?.y??0))),w=Math.max(1,Math.min(1000-x,Number(crop?.w??1000))),h=Math.max(1,Math.min(1000-y,Number(crop?.h??1000)));let sx=im.naturalWidth*x/1000,sy=im.naturalHeight*y/1000,sw=im.naturalWidth*w/1000,sh=im.naturalHeight*h/1000;let scale=Math.min(1,480/Math.max(sw,sh));let c=document.createElement('canvas');c.width=Math.max(1,Math.round(sw*scale));c.height=Math.max(1,Math.round(sh*scale));c.getContext('2d').drawImage(im,sx,sy,sw,sh,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.58))}catch(e){reject(e)}};im.onerror=reject;im.src=URL.createObjectURL(blob)})}
function addItems(){let fs=[...document.getElementById('itemFiles').files];if(!fs.length)return toast('先選單品照');Promise.all(fs.map(read)).then(a=>{a.forEach(img=>db.items.unshift({id:uid(),img,name:'未命名單品',cat:'其他',color:'',tags:'待整理',note:'',last:0}));if(save()){clearInput('itemFiles');toast('已加入衣櫥 ✦');render()}}).catch(e=>{console.error(e);toast('圖片讀取失敗')})}
function clearCloset(){if(!db.items.length)return toast('衣櫥已經是空的');if(confirm('確定清空全部衣櫥單品？')){db.items=[];save();render();toast('衣櫥已清空')}}
function card(x){return `<article class="card"><img src="${x.img||'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="650"><rect width="100%" height="100%" fill="#eee9e5"/><text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" fill="#9b8d86" font-size="28">尚無圖片</text></svg>')}" loading="lazy"><div class="pad"><div class="name">${esc(x.name||'未命名單品')}</div><div class="meta">${esc(x.cat||'待分類')}${x.color?' · '+esc(x.color):''}</div>${(Array.isArray(x.tags)?x.tags.join('、'):x.tags||'').split(/[,，、 ]/).filter(Boolean).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<div class="card-actions"><button class="btn secondary small" onclick="edit('${x.id}')">✎ 編輯</button><button class="btn ghost small" onclick="wear('${x.id}')">穿這件</button><button class="btn danger small" onclick="del('${x.id}')">刪除</button></div></div></article>`}
function edit(id){let x=db.items.find(i=>String(i.id)===String(id));if(!x)return;document.getElementById('mt').textContent='編輯單品';document.getElementById('mb').innerHTML=`<img class="preview" src="${x.img||''}"><div class="form"><div class="field"><label>名稱</label><input id="en" value="${esc(x.name==='未命名單品'?'':x.name)}" placeholder="黑灰格紋長洋裝"></div><div class="field"><label>分類</label><select id="ec">${cats.slice(1).map(c=>`<option ${x.cat===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>顏色</label><input id="eco" value="${esc(x.color)}" placeholder="黑灰、奶油白"></div><div class="field"><label>風格／場合</label><input id="et" value="${esc(Array.isArray(x.tags)?x.tags.join('、'):x.tags)}" placeholder="韓系、甜酷、上班、約會"></div><div class="field"><label>備註</label><textarea id="eno" rows="3">${esc(x.note||'')}</textarea></div><button class="btn" onclick="saveEdit('${x.id}')">儲存</button></div>`;document.getElementById('modal').classList.add('show')}
function saveEdit(id){let x=db.items.find(i=>String(i.id)===String(id));if(!x)return;x.name=en.value.trim()||'未命名單品';x.cat=ec.value;x.color=eco.value.trim();x.tags=et.value.trim();x.note=eno.value.trim();if(save()){closeModal();toast('已更新');render()}}
function closeModal(){document.getElementById('modal')?.classList.remove('show')}
function del(id){if(confirm('確定刪除這件單品？')){db.items=db.items.filter(x=>String(x.id)!==String(id));save();render()}}
function wear(id){let x=db.items.find(i=>String(i.id)===String(id));if(!x)return;x.last=Date.now();save();toast('已記錄今天穿過 ♡');render()}
function render(){let today=document.getElementById('today');if(today)today.textContent=new Date().toLocaleDateString('zh-TW',{month:'2-digit',day:'2-digit',weekday:'short'});let filter=document.getElementById('filter');if(filter)filter.innerHTML=cats.map(c=>`<button class="${cat===c?'on':''}" onclick="cat='${c}';render()">${c}</button>`).join('');let list=cat==='全部'?db.items:db.items.filter(x=>x.cat===cat);let cg=document.getElementById('closetGrid');if(cg)cg.innerHTML=list.length?list.map(card).join(''):`<div class="empty">👗<br><br>這個分類還沒有單品。</div>`;let n=[...db.items].sort((a,b)=>(a.last||0)-(b.last||0)).slice(0,4);let ng=document.getElementById('neglected');if(ng)ng.innerHTML=n.length?n.map(card).join(''):`<div class="empty">🪞<br><br>衣櫥還是空的。</div>`;let dg=document.getElementById('diaryGrid');if(dg)dg.innerHTML=db.diary.length?db.diary.map(d=>`<article><img src="${d.img}"><div class="dbody"><div class="meta">${esc(d.date)}</div><b>${esc(d.note)}</b></div></article>`).join(''):`<div class="empty">📔<br><br>你的穿搭故事會從第一張照片開始。</div>`}
function addDiary(){let fs=[...document.getElementById('diaryFiles').files];if(!fs.length)return toast('先選穿搭照');let note=document.getElementById('note').value.trim()||'今天的穿搭';Promise.all(fs.map(read)).then(a=>{a.forEach(img=>db.diary.unshift({id:uid(),img,note,date:new Date().toLocaleDateString('zh-TW')}));if(save()){clearInput('diaryFiles');document.getElementById('note').value='';toast('已收藏穿搭 ♡');render()}})}
async function makeChatPack(){let fs=[...document.getElementById('splitFiles').files];if(!fs.length)return toast('先選穿搭照');try{let session=await saveSourcePhotos(fs);window.chatPackSession=session;localStorage.setItem('pureAIWardrobeChatSession',session);let p='請幫我整理這批穿搭照，逐張辨識所有可以獨立管理的服飾與配件。不要把整張全身照當成單品。請辨識連衣裙、上衣、下身、外套、鞋子、襪子、包包、配件等；左右兩隻鞋合併成一件鞋子。每件輸出：name、cat、color、tags、note。分類只能使用：上衣、下身、洋裝、外套、鞋子、包包、襪子、配件、其他。若同一件單品在不同照片出現，請標記為同一件，不要重複建立。\n\n【圖片對應規則】每件單品一定要填 photo（照片編號，從1開始）與 crop（以0～1000表示原照片中的裁切框：x、y、w、h）。裁切框請只框住該單品，不要框整張全身照；鞋子左右腳要用同一個單品與能涵蓋兩腳的裁切框。若同一件單品出現在多張照片，選最清楚的一張作為 photo/crop。\n\n只回傳JSON陣列，不要Markdown，不要解釋。格式：[{"name":"黑色瑪莉珍尖頭鞋","cat":"鞋子","color":"黑色","tags":"瑪莉珍、尖頭、低跟","note":"","photo":1,"crop":{"x":100,"y":600,"w":800,"h":300}}]\n\n照片數量：'+fs.length+'。';let box=document.getElementById('chatPack');box.style.display='block';box.innerHTML='<b>整理指令已準備好</b><p>'+esc(p)+'</p><button class="btn small" onclick="copyPack()">複製指令</button><p>網站已暫存這批原始照片。你把照片＋這段指令交給 ChatGPT 後，將回傳的 JSON 貼回下方，網站會依 photo＋crop 自動做出每件單品的圖片。</p>';window.chatPackText=p;toast('照片已暫存，整理包完成 ✦')}catch(e){console.error(e);toast('照片暫存失敗，請再試一次')}}
function copyPack(){navigator.clipboard?.writeText(window.chatPackText||'');toast('已複製 ✦')}
function normalizeImport(raw){let s=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();let start=Math.min(...['[','{'].map(ch=>{let i=s.indexOf(ch);return i<0?Infinity:i}));if(start!==Infinity)s=s.slice(start);let end=Math.max(s.lastIndexOf(']'),s.lastIndexOf('}'));if(end>=0)s=s.slice(0,end+1);let parsed=JSON.parse(s);let a=Array.isArray(parsed)?parsed:(Array.isArray(parsed.items)?parsed.items:(Array.isArray(parsed.data)?parsed.data:[parsed]));return a.filter(x=>x&&typeof x==='object')}
async function importAI(){let btn=document.querySelector('#style button[onclick="importAI()"]');if(btn)btn.disabled=true;try{let raw=document.getElementById('importText')?.value.trim();if(!raw){toast('先貼上 ChatGPT 回傳的 JSON');return}let incoming=normalizeImport(raw);if(!incoming.length){toast('沒有讀到任何單品');return}let session=window.chatPackSession||localStorage.getItem('pureAIWardrobeChatSession');let aliases={'連衣裙':'洋裝','連身裙':'洋裝','裙子':'下身','褲子':'下身','鞋':'鞋子','襪':'襪子','包':'包包','飾品':'配件'};let created=[];for(const x of incoming){let name=String(x.name||x.title||'未命名單品').trim();let c=String(x.cat||x.category||'其他').trim();c=aliases[c]||c;if(!cats.includes(c))c='其他';let color=Array.isArray(x.color)?x.color.join('、'):String(x.color||'').trim();let tags=Array.isArray(x.tags)?x.tags.join('、'):String(x.tags||'').trim();let note=String(x.note||'').trim();let img=x.img||x.image||x.photoUrl||'';if(!img&&x.photo&&x.crop&&session){let blob=await getSourcePhoto(session,Number(x.photo));if(blob)img=await cropBlob(blob,x.crop)}if(!img&&x.sourcePhoto&&x.crop&&session){let blob=await getSourcePhoto(session,Number(x.sourcePhoto));if(blob)img=await cropBlob(blob,x.crop)}created.push({id:uid(),img,name,cat:c,color,tags,note,last:0})}
let old=db.items;db.items=[...created,...old];if(!save()){db.items=old;return}document.getElementById('importText').value='';cat='全部';toast(`已加入 ${created.length} 件 ✦`);tab('closet')}catch(e){console.error('IMPORT_ERROR',e);toast(e?.name==='QuotaExceededError'?'儲存空間不足，請重新整理後再試':'JSON 格式或圖片處理失敗')}finally{if(btn)btn.disabled=false}}
function shop(){let n=document.getElementById('shopName').value.trim()||'這件單品';document.getElementById('shopOut').innerHTML=`<div class="hero"><div class="eyebrow">PURCHASE CHECK</div><h2>${esc(n)}</h2><p>把商品照片也一起上傳給 ChatGPT，我會用你的衣櫥資料分析：可搭配單品、重複程度、使用頻率與購入必要性。</p></div>`}
window.tab=tab;window.addItems=addItems;window.clearInput=clearInput;window.clearCloset=clearCloset;window.edit=edit;window.saveEdit=saveEdit;window.closeModal=closeModal;window.del=del;window.wear=wear;window.addDiary=addDiary;window.makeChatPack=makeChatPack;window.copyPack=copyPack;window.importAI=importAI;window.shop=shop;window.render=render;
render();